# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 953bd182c303d28f263af431562cfae766a62bcd7f247f49e7283a2bd125f7fb2752f43aedc6553d3226e071709446ae725186f479b2287e4f866d2c046038f2

test:
  secret_key_base: acebd63fd0e2ae5383ea1ab23792720dd16393282fbbe8c4007f050a8004edde4549d8da21d8760b250b0b2823941f82a0c66097cfabdedd059f6f044b7d11e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
